version: '3'

services:
  node:
    build:
      context: node
    container_name: node
    tty: true
    ports:
      - "3000:3000"
    command: sh -c "while ! curl --silent --fail db:3306 >/dev/null; do sleep 1; done && node index.js" 
    depends_on:
      - db
    networks: 
      - node-network  

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks: 
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./peopletable.sql:/docker-entrypoint-initdb.d/peopletable.sql
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network    

networks: 
  node-network:
    driver: bridge        